In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr[3]

np.int64(4)

In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
arr2[0][0]

np.int64(1)

In [ ]:
arr2[0,2]

np.int64(3)

In [ ]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8]]])

In [ ]:
arr3[0,0,1]

np.int64(2)

In [ ]:
arr[::-1]

array([4, 3, 2, 1])

In [ ]:
arr_c = arr.copy()

In [ ]:
arr_c[1]

np.int64(2)

In [ ]:
arr_v = arr.view()

In [ ]:
arr_v[1]

np.int64(2)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr_c[1] = 30
arr_c

array([ 1, 30,  3,  4])

In [ ]:
arr.shape

(4,)

In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr3.shape

(1, 2, 4)

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,1,2,2])

In [ ]:
arr.shape

(12,)

In [ ]:
n = arr.reshape(4,3)

In [ ]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 2]])

In [ ]:
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
1
2
2


In [ ]:
for i in arr2:
  for j in i:
    print(j)

1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([1])
arr1 = np.array([1])

In [ ]:
arr = np.concatenate((arr,arr1))
print(arr)

[1 1]


In [ ]:
arr

array([1, 1])

In [ ]:
ar = np.array_split(arr,3)

In [ ]:
print(ar)

[array([1]), array([1]), array([], dtype=int64)]


In [ ]:
x = np.where(arr == 1)

In [ ]:
print(x)

(array([0, 1]),)


In [ ]:
print(np.sort(arr))

[1 1]


In [ ]:
a = np.array([41,42,43,45])

In [ ]:
x = a[[True,False,False,False]]

In [ ]:
print(x)

[41]


In [ ]:
ar = np.array(['a'])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
x = np.eye((10))

In [ ]:
x.flatten()

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [ ]:
np.empty((1,6))

array([[5.25356860e-315, 0.00000000e+000, 5.24595100e-315,
        6.67983752e-310, 6.32291818e+180, 6.01334434e-154]])

In [ ]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [ ]:
np.full((3,3),15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
arr+10

array([11, 12, 13, 14])

In [ ]:
a = np.ones((3,3))

In [ ]:
b = np.ones((3,3))

In [ ]:
np.dot(a,b)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [ ]:
a@b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [ ]:
a.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

mean median mode max min

In [ ]:
np.mean(a)

np.float64(1.0)

In [ ]:
np.median(a)

np.float64(1.0)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
np.max(arr)

np.int64(4)

In [ ]:
np.sum(a)

np.float64(9.0)

In [ ]:
marks = np.array([78,85,92,67,88])

In [ ]:
print(np.max(marks))
print(np.min(marks))
print(np.mean(marks))
print(np.median(marks))
print(np.sum(marks))
print(marks[marks >= 75])

92
67
82.0
85.0
410
[78 85 92 88]


where returns index values